function standardLogicLibrary = initializeLogicLibrary(standardWorkspaceLibrary)
    
    [Rows, ~] = size(standardWorkspaceLibrary);
    standardLogicLibrary = cell(Rows, 1);
    
    for i=1:Rows
        standardLogicLibrary{i} = BasicBuildingBlocks(standardWorkspaceLibrary{i, 1}, ... 
                                                   standardWorkspaceLibrary{i, 2}, ... 
                                                   standardWorkspaceLibrary{i, 3}, ... 
                                                   standardWorkspaceLibrary{i, 4}, ... 
                                                   standardWorkspaceLibrary{i, 5}, ... 
                                                   standardWorkspaceLibrary{i, 6}, ...
                                                   standardWorkspaceLibrary{i, 7}, ... 
                                                   standardWorkspaceLibrary{i, 8}, ...
                                                   standardWorkspaceLibrary{i, 9});
        %disp(i);
    end
end
