function [ MED, ER ] = LongTerm_MED_ER( listOfStructuralBuildingBlocks, ...
                                        InputDistributionA, InputDistributionB)

    %FUNCTION DESCRIPTION: 
    %
    % List of all parameters that are needed to be calculated:
    % I) CURRENT LEVEL VARIABLES (20):
        
        % 1) using the function "CurrentNumOfPositiveNodes.m"
        % 1.1- Current Number Of Positive Nodes for Cin = 0, and Cout = 0 
        % 1.2- Current Number Of Positive Nodes for Cin = 0, and Cout = 1 
        % 1.3- Current Number Of Positive Nodes for Cin = 1, and Cout = 0
        % 1.4- Current Number Of Positive Nodes for Cin = 1, and Cout = 1 
        
        % 2) using the function "CurrentNumOfNegativeNodes.m"
        % 2.1- Current Number Of Negative Nodes for Cin = 0, and Cout = 0 
        % 2.2- Current Number Of Negative Nodes for Cin = 0, and Cout = 1 
        % 2.3- Current Number Of Negative Nodes for Cin = 1, and Cout = 0
        % 2.4- Current Number Of Negative Nodes for Cin = 1, and Cout = 1 
        
        % 3) using the function "CurrentNumOfZeroNodes.m"
        % 3.1- Current Number Of Zero Nodes for Cin = 0, and Cout = 0 
        % 3.2- Current Number Of Zero Nodes for Cin = 0, and Cout = 1 
        % 3.3- Current Number Of Zero Nodes for Cin = 1, and Cout = 0
        % 3.4- Current Number Of Zero Nodes for Cin = 1, and Cout = 1 
        
        
        % 4) using the function "CurrentSumOfPositiveErrorValues.m"
        % 4.1- Current Sum Of Positive Error Values for Cin = 0, and Cout = 0 
        % 4.2- Current Sum Of Positive Error Values for Cin = 0, and Cout = 1 
        % 4.3- Current Sum Of Positive Error Values for Cin = 1, and Cout = 0
        % 4.4- Current Sum Of Positive Error Values for Cin = 1, and Cout = 1 
        
        % 5) using the function "CurrentSumOfNegativeErrorValues.m"
        % 5.1- Current Sum Of Negative Error Values for Cin = 0, and Cout = 0 
        % 5.2- Current Sum Of Negative Error Values for Cin = 0, and Cout = 1 
        % 5.3- Current Sum Of Negative Error Values for Cin = 1, and Cout = 0
        % 5.4- Current Sum Of Negative Error Values for Cin = 1, and Cout = 1 
        
    % II) CUMULATIVE VARIABLES (10):
        
        % 1) using the function  "CumulativeSADPlus.m"
        % 1.1) Cumulative Sum of Absolute Positive EDs from bit 0 to current for Cout = 0 
        % 1.1) Cumulative Sum of Absolute Positive EDs from bit 0 to current for Cout = 1
        
        % 2) using the function  "CumulativeSADMinus.m"
        % 2.1) Cumulative Sum of Absolute Negative EDs from bit 0 to current for Cout = 0 
        % 2.2) Cumulative Sum of Absolute Negative EDs from bit 0 to current for Cout = 1
        
        
        % 3) using the function  "CumulativeNumOfPostiveNodes.m"
        % 3.1) Cumulative Number Of Positive Nodes from bit 0 to current for Cout = 0 
        % 3.2) Cumulative Number Of Positive Nodes from bit 0 to current for Cout = 1
        
        % 4) using the function  "CumulativeNumOfNegativeNodes.m"
        % 4.1) Cumulative Number Of Negative Nodes from bit 0 to current for Cout = 0 
        % 4.2) Cumulative Number Of Negative Nodes from bit 0 to current for Cout = 1
        
        % 5) using the function  "CumulativeNumOfZeroNodes.m"
        % 5.1) Cumulative Number Of Zero Nodes from bit 0 to current for Cout = 0 
        % 5.2) Cumulative Number Of Zero Nodes from bit 0 to current for Cout = 1
        
        
    % Step 1) Variable initialization ------------------------------------------
    AdderWidth = size(listOfStructuralBuildingBlocks, 2);
    DA = InputDistributionA;
    DB = InputDistributionB;
    Blocks = listOfStructuralBuildingBlocks;
    
    
    carryInProbability = 0;
    
    tempCarryInProbability = 0;


    previousNumOfP_Norm_CoBar = 0;
    previousNumOfP_Norm_Co    = 0;
    previousNumOfP_Ab0_CoBar  = 0;
    previousNumOfP_Ab0_Co     = 0;
    previousNumOfP_Ab1_CoBar  = 0;
    previousNumOfP_Ab1_Co     = 0;
    previousNumOfN_Norm_CoBar = 0; 
    previousNumOfN_Norm_Co    = 0;
    previousNumOfN_Ab0_CoBar  = 0;
    previousNumOfN_Ab0_Co     = 0;
    previousNumOfN_Ab1_CoBar  = 0;
    previousNumOfN_Ab1_Co     = 0;
    previousNumOfZ_Co         = 0;
    previousNumOfZ_CoBar      = 0;
    
    tempPreviousNumOfP_Norm_CoBar = 0;
    tempPreviousNumOfP_Norm_Co    = 0;
    tempPreviousNumOfP_Ab0_CoBar  = 0;
    tempPreviousNumOfP_Ab0_Co     = 0;
    tempPreviousNumOfP_Ab1_CoBar  = 0;
    tempPreviousNumOfP_Ab1_Co     = 0;
    tempPreviousNumOfN_Norm_CoBar = 0; 
    tempPreviousNumOfN_Norm_Co    = 0;
    tempPreviousNumOfN_Ab0_CoBar  = 0;
    tempPreviousNumOfN_Ab0_Co     = 0;
    tempPreviousNumOfN_Ab1_CoBar  = 0;
    tempPreviousNumOfN_Ab1_Co     = 0;
    tempPreviousNumOfZ_Co         = 0;
    tempPreviousNumOfZ_CoBar      = 0;
    
    
    previousSADPlus_Norm_CoBar  = 0;
    previousSADPlus_Norm_Co     = 0;
    previousSADPlus_Ab0_CoBar   = 0; 
    previousSADPlus_Ab0_Co      = 0;
    previousSADPlus_Ab1_CoBar   = 0;
    previousSADPlus_Ab1_Co      = 0;
    previousSADMinus_Norm_CoBar = 0; 
    previousSADMinus_Norm_Co    = 0;
    previousSADMinus_Ab0_CoBar  = 0; 
    previousSADMinus_Ab0_Co     = 0;
    previousSADMinus_Ab1_CoBar  = 0;
    previousSADMinus_Ab1_Co     = 0;
    
    tempPreviousSADPlus_Norm_CoBar  = 0;
    tempPreviousSADPlus_Norm_Co     = 0;
    tempPreviousSADPlus_Ab0_CoBar   = 0; 
    tempPreviousSADPlus_Ab0_Co      = 0;
    tempPreviousSADPlus_Ab1_CoBar   = 0;
    tempPreviousSADPlus_Ab1_Co      = 0;
    tempPreviousSADMinus_Norm_CoBar = 0; 
    tempPreviousSADMinus_Norm_Co    = 0;
    tempPreviousSADMinus_Ab0_CoBar  = 0; 
    tempPreviousSADMinus_Ab0_Co     = 0;
    tempPreviousSADMinus_Ab1_CoBar  = 0;
    tempPreviousSADMinus_Ab1_Co     = 0;
    % Step 1) END --------------------------------------------------------------
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% STEP 2) %%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Step 2) % for the first Block, everything should be calculated manually 
    % TIP: for Block{1} we always have cin = 0
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    % =====================================================================
    % 2.1) CUMULATIVE number of Positive, Negative and Zero Nodes in Block{1}: 
    % =====================================================================
    
    % ==============================POSITIVE===============================
        [ currentNumOfPositive_CinBar_CoBar_Norm, ...
        currentNumOfPositive_CinBar_CoBar_Ab0, ...
        currentNumOfPositive_CinBar_CoBar_Ab1, ...
        currentNumOfPositive_CinBar_Co_Norm, ...
        currentNumOfPositive_CinBar_Co_Ab0, ...
        currentNumOfPositive_CinBar_Co_Ab1, ...
        ~, ...
        ~, ...
        ~, ...
        ~, ...
        ~, ...
        ~ ] = ...
        CurrentNumOfPositiveNodes( 0, ... 
                                   Blocks{1}, ...
                                   DA(1), ... 
                                   DB(1));
       
        tempPreviousNumOfP_Norm_CoBar = currentNumOfPositive_CinBar_CoBar_Norm;
        tempPreviousNumOfP_Norm_Co    = currentNumOfPositive_CinBar_Co_Norm;
        tempPreviousNumOfP_Ab0_CoBar  = currentNumOfPositive_CinBar_CoBar_Ab0;
        tempPreviousNumOfP_Ab0_Co     = currentNumOfPositive_CinBar_Co_Ab0;
        tempPreviousNumOfP_Ab1_CoBar  = currentNumOfPositive_CinBar_CoBar_Ab1;
        tempPreviousNumOfP_Ab1_Co     = currentNumOfPositive_CinBar_Co_Ab1;

    % ==============================NEGATIVE===============================
        [ currentNumOfNegative_CinBar_CoBar_Norm, ...
        currentNumOfNegative_CinBar_CoBar_Ab0, ...
        currentNumOfNegative_CinBar_CoBar_Ab1, ...
        currentNumOfNegative_CinBar_Co_Norm, ...
        currentNumOfNegative_CinBar_Co_Ab0, ...
        currentNumOfNegative_CinBar_Co_Ab1, ...
        ~, ...
        ~, ...
        ~, ...
        ~, ...
        ~, ...
        ~ ] = ...
        CurrentNumOfNegativeNodes( 0, ... 
                                   Blocks{1}, ...
                                   DA(1), ... 
                                   DB(1));
        
        tempPreviousNumOfN_Norm_CoBar = currentNumOfNegative_CinBar_CoBar_Norm; 
        tempPreviousNumOfN_Norm_Co    = currentNumOfNegative_CinBar_Co_Norm;
        tempPreviousNumOfN_Ab0_CoBar  = currentNumOfNegative_CinBar_CoBar_Ab0;
        tempPreviousNumOfN_Ab0_Co     = currentNumOfNegative_CinBar_Co_Ab0;
        tempPreviousNumOfN_Ab1_CoBar  = currentNumOfNegative_CinBar_CoBar_Ab1;
        tempPreviousNumOfN_Ab1_Co     = currentNumOfNegative_CinBar_Co_Ab1;
    
    % ===============================ZERO==================================
    [currentNumOfZero_CinBar_CoBar, ...
    currentNumOfZero_CinBar_Co, ...
    ~, ...
    ~] = ...
    CurrentNumOfZeroNodes(0, ...
                          Blocks{1}, ...
                          DA(1), ...
                          DB(1));
    tempPreviousNumOfZ_Co = currentNumOfZero_CinBar_Co;
    tempPreviousNumOfZ_CoBar = currentNumOfZero_CinBar_CoBar;
    
    
    % =====================================================================
    % 2.2) CUMULATIVE SAD of Positive and Negative Error Values Block{0}: 
    % =====================================================================
    
    % =========================== POSITIVE SAD ============================
        [ CurrentSumPlus_CinBar_CoBar_Norm, ...
        CurrentSumPlus_CinBar_CoBar_Ab0, ...
        CurrentSumPlus_CinBar_CoBar_Ab1, ...
        CurrentSumPlus_CinBar_Co_Norm, ...
        CurrentSumPlus_CinBar_Co_Ab0, ...
        CurrentSumPlus_CinBar_Co_Ab1, ...
        ~, ...
        ~, ...
        ~, ...
        ~, ...
        ~, ...
        ~ ] = ... 
        CurrentSumOfPositiveErrorValues( 0, ... 
                                         Blocks{1}, ...
                                         DA(1), ... 
                                         DB(1));
        
        tempPreviousSADPlus_Norm_CoBar  = CurrentSumPlus_CinBar_CoBar_Norm;
        tempPreviousSADPlus_Norm_Co     = CurrentSumPlus_CinBar_Co_Norm;
        tempPreviousSADPlus_Ab0_CoBar   = CurrentSumPlus_CinBar_CoBar_Ab0; 
        tempPreviousSADPlus_Ab0_Co      = CurrentSumPlus_CinBar_Co_Ab0;
        tempPreviousSADPlus_Ab1_CoBar   = CurrentSumPlus_CinBar_CoBar_Ab1;
        tempPreviousSADPlus_Ab1_Co      = CurrentSumPlus_CinBar_Co_Ab1;
        
        
    % =========================== NEGATIVE SAD ============================
        [ CurrentSumMinus_CinBar_CoBar_Norm, ...
        CurrentSumMinus_CinBar_CoBar_Ab0, ...
        CurrentSumMinus_CinBar_CoBar_Ab1, ...
        CurrentSumMinus_CinBar_Co_Norm, ...
        CurrentSumMinus_CinBar_Co_Ab0, ...
        CurrentSumMinus_CinBar_Co_Ab1, ...
        ~, ...
        ~, ...
        ~, ...
        ~, ...
        ~, ...
        ~ ] = ...
        CurrentSumOfNegativeErrorValues( 0, ... 
                                         Blocks{1}, ...
                                         DA(1), ... 
                                         DB(1));
    
        tempPreviousSADMinus_Norm_CoBar = CurrentSumMinus_CinBar_CoBar_Norm; 
        tempPreviousSADMinus_Norm_Co    = CurrentSumMinus_CinBar_Co_Norm;
        tempPreviousSADMinus_Ab0_CoBar  = CurrentSumMinus_CinBar_CoBar_Ab0; 
        tempPreviousSADMinus_Ab0_Co     = CurrentSumMinus_CinBar_Co_Ab0;
        tempPreviousSADMinus_Ab1_CoBar  = CurrentSumMinus_CinBar_CoBar_Ab1;
        tempPreviousSADMinus_Ab1_Co     = CurrentSumMinus_CinBar_Co_Ab1;

    
    % =====================================================================
    % 2.3) calculating the probability of carry out  
    % =====================================================================
    
    % ===================== CARRY OUT PROBABILITY =========================
    tempCarryInProbability = CurrentCarryOutProbability(0,Blocks{1}, DA(1), DB(1));
    
    % =====================================================================
    % 2.4) from the next Block's point of view, all cumulative variables of
        % the current block are known as "previous" variables;
    % =====================================================================
    
    % ========================== DATA TRANSFER ============================
    
    previousNumOfP_Norm_CoBar = tempPreviousNumOfP_Norm_CoBar;
    previousNumOfP_Norm_Co    = tempPreviousNumOfP_Norm_Co;
    previousNumOfP_Ab0_CoBar  = tempPreviousNumOfP_Ab0_CoBar;
    previousNumOfP_Ab0_Co     = tempPreviousNumOfP_Ab0_Co;
    previousNumOfP_Ab1_CoBar  = tempPreviousNumOfP_Ab1_CoBar;
    previousNumOfP_Ab1_Co     = tempPreviousNumOfP_Ab1_Co;
    previousNumOfN_Norm_CoBar = tempPreviousNumOfN_Norm_CoBar; 
    previousNumOfN_Norm_Co    = tempPreviousNumOfN_Norm_Co;
    previousNumOfN_Ab0_CoBar  = tempPreviousNumOfN_Ab0_CoBar;
    previousNumOfN_Ab0_Co     = tempPreviousNumOfN_Ab0_Co;
    previousNumOfN_Ab1_CoBar  = tempPreviousNumOfN_Ab1_CoBar;
    previousNumOfN_Ab1_Co     = tempPreviousNumOfN_Ab1_Co;
    previousNumOfZ_Co         = tempPreviousNumOfZ_Co;
    previousNumOfZ_CoBar      = tempPreviousNumOfZ_CoBar;
    
    carryInProbability = tempCarryInProbability;

    previousSADPlus_Norm_CoBar  = tempPreviousSADPlus_Norm_CoBar;
    previousSADPlus_Norm_Co     = tempPreviousSADPlus_Norm_Co;
    previousSADPlus_Ab0_CoBar   = tempPreviousSADPlus_Ab0_CoBar; 
    previousSADPlus_Ab0_Co      = tempPreviousSADPlus_Ab0_Co;
    previousSADPlus_Ab1_CoBar   = tempPreviousSADPlus_Ab1_CoBar;
    previousSADPlus_Ab1_Co      = tempPreviousSADPlus_Ab1_Co;
    previousSADMinus_Norm_CoBar = tempPreviousSADMinus_Norm_CoBar; 
    previousSADMinus_Norm_Co    = tempPreviousSADMinus_Norm_Co;
    previousSADMinus_Ab0_CoBar  = tempPreviousSADMinus_Ab0_CoBar; 
    previousSADMinus_Ab0_Co     = tempPreviousSADMinus_Ab0_Co;
    previousSADMinus_Ab1_CoBar  = tempPreviousSADMinus_Ab1_CoBar;
    previousSADMinus_Ab1_Co     = tempPreviousSADMinus_Ab1_Co;
    
    % Step 2) END ---------------------------------------------------------
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% STEP 3) %%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Step 3) Calculating MED(2) & ER(2) to MED(AdderWidth) & ER(AdderWidth)
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    for i=2:AdderWidth
       
        bitPosition = i-1;
        
        %============================= SAD PLUS ===========================
        % 0.1) Calculating the cumulative SADPlus for the current Stage
        %==================================================================
        
        [tempPreviousSADPlus_Norm_CoBar, ...
         tempPreviousSADPlus_Norm_Co, ...
         tempPreviousSADPlus_Ab0_CoBar, ...
         tempPreviousSADPlus_Ab0_Co, ...
         tempPreviousSADPlus_Ab1_CoBar, ...
         tempPreviousSADPlus_Ab1_Co ...
          ] = ...
          CumulativeSADPlus ... 
          ( previousSADPlus_Norm_CoBar, previousSADPlus_Norm_Co, ...
            previousSADPlus_Ab0_CoBar, previousSADPlus_Ab0_Co, ...
            previousSADPlus_Ab1_CoBar, previousSADPlus_Ab1_Co, ...
            ...
            previousSADMinus_Norm_CoBar, previousSADMinus_Norm_Co, ...
            previousSADMinus_Ab0_CoBar, previousSADMinus_Ab0_Co, ...
            previousSADMinus_Ab1_CoBar, previousSADMinus_Ab1_Co, ...
            ...
            previousNumOfP_Norm_CoBar, previousNumOfP_Norm_Co, ...
            previousNumOfP_Ab0_CoBar, previousNumOfP_Ab0_Co, ...
            previousNumOfP_Ab1_CoBar, previousNumOfP_Ab1_Co, ...
            ...
            previousNumOfN_Norm_CoBar, previousNumOfN_Norm_Co, ...
            previousNumOfN_Ab0_CoBar, previousNumOfN_Ab0_Co, ...
            previousNumOfN_Ab1_CoBar, previousNumOfN_Ab1_Co, ...
            ...
            previousNumOfZ_CoBar, previousNumOfZ_Co, ...
            ...
            carryInProbability, Blocks{i}, ...
            DA(i), DB(i), ...
            bitPosition);
        
        %============================= SAD MINUS ==========================
        % 0.2) Calculating the cumulative SADMinus for the current Stage
        %==================================================================
        
        [tempPreviousSADMinus_Norm_CoBar, ...
         tempPreviousSADMinus_Norm_Co, ...
         tempPreviousSADMinus_Ab0_CoBar, ...
         tempPreviousSADMinus_Ab0_Co, ...
         tempPreviousSADMinus_Ab1_CoBar, ...
         tempPreviousSADMinus_Ab1_Co ...
          ] = ...
          CumulativeSADMinus ...
          ( previousSADPlus_Norm_CoBar, previousSADPlus_Norm_Co, ...
            previousSADPlus_Ab0_CoBar, previousSADPlus_Ab0_Co, ...
            previousSADPlus_Ab1_CoBar, previousSADPlus_Ab1_Co, ...
            ...
            previousSADMinus_Norm_CoBar, previousSADMinus_Norm_Co, ...
            previousSADMinus_Ab0_CoBar, previousSADMinus_Ab0_Co, ...
            previousSADMinus_Ab1_CoBar, previousSADMinus_Ab1_Co, ...
            ...
            previousNumOfP_Norm_CoBar, previousNumOfP_Norm_Co, ...
            previousNumOfP_Ab0_CoBar, previousNumOfP_Ab0_Co, ...
            previousNumOfP_Ab1_CoBar, previousNumOfP_Ab1_Co, ...
            ...
            previousNumOfN_Norm_CoBar, previousNumOfN_Norm_Co, ...
            previousNumOfN_Ab0_CoBar, previousNumOfN_Ab0_Co, ...
            previousNumOfN_Ab1_CoBar, previousNumOfN_Ab1_Co, ...
            ...
            previousNumOfZ_CoBar, previousNumOfZ_Co, ...
            ...
            carryInProbability, Blocks{i}, ...
            DA(i), DB(i), ...
            bitPosition);
        
        %============================= CARRY ==============================
        % 1) CarryIn Probability of the next stage
        %==================================================================
        tempCarryInProbability = CurrentCarryOutProbability( carryInProbability, Blocks{i}, DA(i), DB(i));
        
        %============================= POSITIVE ===========================
        % 2.1) Cumulative number of Previous Positive Nodes for the next Block
        %==================================================================
        [ tempPreviousNumOfP_Norm_CoBar, tempPreviousNumOfP_Norm_Co, ...
          tempPreviousNumOfP_Ab0_CoBar, tempPreviousNumOfP_Ab0_Co, ...
          tempPreviousNumOfP_Ab1_CoBar, tempPreviousNumOfP_Ab1_Co] = ... 
           CumulativeNumOfPostiveNodes ... 
         ( previousNumOfP_Norm_CoBar, previousNumOfP_Norm_Co, ...
           previousNumOfP_Ab0_CoBar, previousNumOfP_Ab0_Co, ...
           previousNumOfP_Ab1_CoBar, previousNumOfP_Ab1_Co, ...
           previousNumOfN_Norm_CoBar, previousNumOfN_Norm_Co, ...
           previousNumOfN_Ab0_CoBar, previousNumOfN_Ab0_Co, ...
           previousNumOfN_Ab1_CoBar, previousNumOfN_Ab1_Co, ...
           previousNumOfZ_Co, previousNumOfZ_CoBar, ... 
           carryInProbability, Blocks{i}, ...
           DA(i), DB(i));
        
        %============================= NEGATIVE ===========================
        % 2.2) Cumulative number of Previous Negative Nodes for the next Block
        %==================================================================
        [ tempPreviousNumOfN_Norm_CoBar, tempPreviousNumOfN_Norm_Co, ...
          tempPreviousNumOfN_Ab0_CoBar, tempPreviousNumOfN_Ab0_Co, ...
          tempPreviousNumOfN_Ab1_CoBar, tempPreviousNumOfN_Ab1_Co] = ... 
           CumulativeNumOfNegativeNodes ... 
         ( previousNumOfP_Norm_CoBar, previousNumOfP_Norm_Co, ...
           previousNumOfP_Ab0_CoBar, previousNumOfP_Ab0_Co, ...
           previousNumOfP_Ab1_CoBar, previousNumOfP_Ab1_Co, ...
           previousNumOfN_Norm_CoBar, previousNumOfN_Norm_Co, ...
           previousNumOfN_Ab0_CoBar, previousNumOfN_Ab0_Co, ...
           previousNumOfN_Ab1_CoBar, previousNumOfN_Ab1_Co, ...
           previousNumOfZ_Co, previousNumOfZ_CoBar, ... 
           carryInProbability, Blocks{i}, ...
           DA(i), DB(i));
        
        %============================= ZERO ===============================
        % 2.3) Cumulative number of Previous Zero Nodes for the next Block
        %==================================================================
        [ tempPreviousNumOfZ_Co, tempPreviousNumOfZ_CoBar ] = ...
           CumulativeNumOfZeroNodes ... 
         ( previousNumOfP_Norm_CoBar, previousNumOfP_Norm_Co, ...
           previousNumOfP_Ab0_CoBar,  previousNumOfP_Ab0_Co, ...
           previousNumOfP_Ab1_CoBar,  previousNumOfP_Ab1_Co, ...
           previousNumOfN_Norm_CoBar, previousNumOfN_Norm_Co, ...
           previousNumOfN_Ab0_CoBar,  previousNumOfN_Ab0_Co, ...
           previousNumOfN_Ab1_CoBar,  previousNumOfN_Ab1_Co, ...
           previousNumOfZ_Co, previousNumOfZ_CoBar, ... 
           carryInProbability, Blocks{i}, ...
           DA(i), DB(i));
            
        % ========================== DATA TRANSFER ========================
        

            previousNumOfP_Norm_CoBar = tempPreviousNumOfP_Norm_CoBar;
            previousNumOfP_Norm_Co    = tempPreviousNumOfP_Norm_Co;
            previousNumOfP_Ab0_CoBar  = tempPreviousNumOfP_Ab0_CoBar;
            previousNumOfP_Ab0_Co     = tempPreviousNumOfP_Ab0_Co;
            previousNumOfP_Ab1_CoBar  = tempPreviousNumOfP_Ab1_CoBar;
            previousNumOfP_Ab1_Co     = tempPreviousNumOfP_Ab1_Co;
            previousNumOfN_Norm_CoBar = tempPreviousNumOfN_Norm_CoBar; 
            previousNumOfN_Norm_Co    = tempPreviousNumOfN_Norm_Co;
            previousNumOfN_Ab0_CoBar  = tempPreviousNumOfN_Ab0_CoBar;
            previousNumOfN_Ab0_Co     = tempPreviousNumOfN_Ab0_Co;
            previousNumOfN_Ab1_CoBar  = tempPreviousNumOfN_Ab1_CoBar;
            previousNumOfN_Ab1_Co     = tempPreviousNumOfN_Ab1_Co;
            previousNumOfZ_Co         = tempPreviousNumOfZ_Co;
            previousNumOfZ_CoBar      = tempPreviousNumOfZ_CoBar;

            carryInProbability = tempCarryInProbability;

            previousSADPlus_Norm_CoBar  = tempPreviousSADPlus_Norm_CoBar;
            previousSADPlus_Norm_Co     = tempPreviousSADPlus_Norm_Co;
            previousSADPlus_Ab0_CoBar   = tempPreviousSADPlus_Ab0_CoBar; 
            previousSADPlus_Ab0_Co      = tempPreviousSADPlus_Ab0_Co;
            previousSADPlus_Ab1_CoBar   = tempPreviousSADPlus_Ab1_CoBar;
            previousSADPlus_Ab1_Co      = tempPreviousSADPlus_Ab1_Co;
            previousSADMinus_Norm_CoBar = tempPreviousSADMinus_Norm_CoBar; 
            previousSADMinus_Norm_Co    = tempPreviousSADMinus_Norm_Co;
            previousSADMinus_Ab0_CoBar  = tempPreviousSADMinus_Ab0_CoBar; 
            previousSADMinus_Ab0_Co     = tempPreviousSADMinus_Ab0_Co;
            previousSADMinus_Ab1_CoBar  = tempPreviousSADMinus_Ab1_CoBar;
            previousSADMinus_Ab1_Co     = tempPreviousSADMinus_Ab1_Co;
    end
    
    % Step 3) END --------------------------------------------------------------
    MED = ...
          previousSADPlus_Norm_CoBar  + previousSADPlus_Norm_Co  + ...
          previousSADPlus_Ab0_CoBar   + previousSADPlus_Ab0_Co   + ...
          previousSADPlus_Ab1_CoBar   + previousSADPlus_Ab1_Co   + ...
          ...
          previousSADMinus_Norm_CoBar + previousSADMinus_Norm_Co + ...
          previousSADMinus_Ab0_CoBar  + previousSADMinus_Ab0_Co  + ...
          previousSADMinus_Ab1_CoBar  + previousSADMinus_Ab1_Co;


    ER = 1 - (previousNumOfZ_Co + previousNumOfZ_CoBar);
end

